"""add is_selected to recipes

Revision ID: 2e7a324c567a
Revises: e7b5cb225a11
Create Date: 2025-12-24 17:12:25.843172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e7a324c567a'
down_revision: Union[str, Sequence[str], None] = 'e7b5cb225a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('is_selected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'is_selected')
    # ### end Alembic commands ###
